name: berezhok
description: "Berezhok — geolocation food sharing platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # Networking
  dio: ^5.7.0

  # Local storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.5

  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Location
  geolocator: ^13.0.2
  permission_handler: ^11.3.1

  # QR Code
  qr_flutter: ^4.1.0

  # Images
  cached_network_image: ^3.4.1

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.3.1
  mask_text_input_formatter: ^2.9.0
  flutter_dotenv: ^5.2.1
  app_links: ^6.0.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env
