// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArjDbeK7xM2FaLjDr9PBCHcig3fzOadJg',
    appId: '1:655705675114:web:b20999b25b320561014113',
    messagingSenderId: '655705675114',
    projectId: 'berezhok-mobile',
    authDomain: 'berezhok-mobile.firebaseapp.com',
    storageBucket: 'berezhok-mobile.firebasestorage.app',
    measurementId: 'G-G56G2S7Y28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcHO5XpEgHkxk9ZcAU3nkiHl09y5vrXuk',
    appId: '1:655705675114:android:365b51133f562c22014113',
    messagingSenderId: '655705675114',
    projectId: 'berezhok-mobile',
    storageBucket: 'berezhok-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2HPI8Zf3DiUCDDP4AjcTrz7TlnSQwmk',
    appId: '1:655705675114:ios:2ecbfb6957144e4a014113',
    messagingSenderId: '655705675114',
    projectId: 'berezhok-mobile',
    storageBucket: 'berezhok-mobile.firebasestorage.app',
    iosBundleId: 'ru.berezhok.berezhok',
  );
}
